/* tslint:disable */
/* eslint-disable */
/**
 * Woof Enactus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreatePartnerDto
 */
export interface CreatePartnerDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    postal: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    website: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    type: CreatePartnerDtoTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreatePartnerDtoTypeEnum {
    VET = 'VET',
    ORG = 'ORG',
    SHOP = 'SHOP',
    SHELTER = 'SHELTER'
}

