/* tslint:disable */
/* eslint-disable */
/**
 * Woof Enactus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GetAllPartnersResponse
 */
export interface GetAllPartnersResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetAllPartnersResponse
     */
    ok: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAllPartnersResponse
     */
    data?: Array<string>;
    /**
     * 
     * @type {any}
     * @memberof GetAllPartnersResponse
     */
    message?: any;
    /**
     * 
     * @type {any}
     * @memberof GetAllPartnersResponse
     */
    error?: any;
}
