/* tslint:disable */
/* eslint-disable */
/**
 * Woof Enactus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GetAllPartnersResponse
 */
export interface GetAllPartnersResponse {
    /**
     * Jeżeli zapytanie było poprawne i znaleziono żądany zasób to jest ustawione na TRUE. W każdym innym przypadku FALSE.
     * @type {boolean}
     * @memberof GetAllPartnersResponse
     */
    ok: boolean;
    /**
     * Zawiera żądany zasób, jeśli taki istnieje
     * @type {any}
     * @memberof GetAllPartnersResponse
     */
    data?: any;
    /**
     * Zawiera wiadomość o błędzie
     * @type {string}
     * @memberof GetAllPartnersResponse
     */
    message?: string;
    /**
     * Zawiera szczegółowy opis błędu, dostępne tylko na devie
     * @type {string}
     * @memberof GetAllPartnersResponse
     */
    error?: string;
}
