
services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    hostname: database
    env_file:
      - .env

  backend:
    hostname: backend
    image: woof-enactus-backend:latest
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    hostname: frontend
    image: woof-enactus-frontend:latest
    env_file:
      - .env
    depends_on:
      - backend

  cms:
    build:
      context: .
      dockerfile: ./apps/blog/prod.Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./apps/blog:/apps/blog:cached
    env_file:
      - ./apps/blog/.env
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=aws-0-eu-central-1.pooler.supabase.com
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres.wshnqqdekglkwbkqysrj
      - DATABASE_PASSWORD=d87ytasdiuafdoayisdlfgaid
      - DATABASE_SSL=true
      - NODE_ENV=production



