# Ten compose jest przeznaczony do uruchamiania aplikacji w wersji produkcyjnej
services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    hostname: database
    env_file:
      - .env

  backend:
    hostname: backend
    image: woof-enactus-backend:latest
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    hostname: frontend
    image: woof-enactus-frontend:latest
    env_file:
      - .env
    depends_on:
      - backend

  blog:
    hostname: blog
    image: woof-enactus-blog:latest
    env_file:
      - .env
    depends_on:
      - database
