import type { Metadata } from "next";
import Providers from "./providers";
import { Footer } from "@/components/Footer";
import { Nav } from "@/components/Navbar";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body>
        <Providers>
          <Nav></Nav>
          <Container flex={1}>{children}</Container>
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
