name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build Docker images and push to GCP Aritfact Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: angular-amp-459415-h8
          workload_identity_provider: projects/782854916885/locations/global/workloadIdentityPools/haumaps/providers/github
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get image tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push Frontend Image
        uses: docker/build-push-action@v6
        with:
          push: false
          file: prod.Dockerfile
          target: frontend
          tags: |
            europe-north1-docker.pkg.dev/angular-amp-459415-h8/haumaps/haumaps-frontend:${{ steps.get-tag.outputs.short_ref }}
            europe-north1-docker.pkg.dev/angular-amp-459415-h8/haumaps/haumaps-frontend:latest

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: prod.Dockerfile
          target: backend
          tags: |
            europe-north1-docker.pkg.dev/angular-amp-459415-h8/haumaps/haumaps-backend:${{ steps.get-tag.outputs.short_ref }}
            europe-north1-docker.pkg.dev/angular-amp-459415-h8/haumaps/haumaps-backend:latest
